### ISSUE TITLE
大佬，为什么会报找不到vite模块啊？

### ISSUE THREAD

**Issue by echofly** [codercup/unibest-hbx#1]
#### 我看package.json中没有写vite依赖，项目能正常运行，就是会有这个提示

![image](https://github.com/codercup/unibest-hbx/assets/36875450/501b4273-2134-4f11-acc8-d951a1fe1b44)

**Comment by echofly** [comment]
搞清楚了，Vite服务在hbx中

**Comment by codercup** [comment]
工作太忙了，精力不足。本项目大家自己维护，欢迎PR。

**Comment by codercup** [comment]
@echofly 项目交给你维护如何？我把你拉进来

**Comment by codercup** [comment]
> @echofly 项目交给你维护如何？我把你拉进来

已经邀请你了~

**Comment by echofly** [comment]
OK，到时不懂的还请多指教

**Comment by Xiphin** [comment]
Resolved
