### ISSUE TITLE
unplugin-auto-import未生效，不会生成auto-import.d.ts，导致编辑器报红

### ISSUE THREAD

**Issue by echofly** [codercup/unibest-hbx#2]
![image](https://github.com/codercup/unibest-hbx/assets/36875450/5810412f-890a-4d4e-bd67-7b38422a8d83)

**Comment by echofly** [comment]
找到原因了，想问下大佬为什么要把dts关掉呢？

![image](https://github.com/codercup/unibest-hbx/assets/36875450/dd317de6-c6fb-46eb-ac99-83ef3ed67319)

**Comment by codercup** [comment]
工作太忙了，精力不足。本项目大家自己维护，欢迎PR。

**Comment by codercup** [comment]
已经解决，拉新代码即可
